import Button from '@/components/common/ui/Button';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useRef, useState } from 'react';
import { SkeletonView } from './SkeletonVIew';
import EmptyState from '@/components/common/EmptyState';
import { Compass, WifiOff } from 'lucide-react';
import AnalyzingLoader from './AnalyzingLoader';
import { RecommendData } from '@/shared/domain/recommend/types';
import { recommendationsKey } from '@/shared/domain/recommend/queryKeys';
import MarqueeRow from './MarqueeRow';

const RecommendContainer = () => {
  const queryClient = useQueryClient();
  const autoGenerated = useRef(false);

  const {
    data: recommend,
    error: loadError,
    isPending,
    isSuccess,
  } = useQuery<RecommendData>({
    queryKey: recommendationsKey.all,
    queryFn: async () => {
      const res = await fetch('/api/recommend-v2', { method: 'GET' });
      if (!res.ok) {
        const body = await res.json();
        throw new Error(body.error ?? '불러오기 실패');
      }
      return res.json();
    },
    staleTime: 1000 * 60 * 5,
  });
  const {
    mutate: generate,
    isPending: generating,
    error: generateError,
  } = useMutation({
    mutationFn: async () => {
      const res = await fetch('/api/recommend-v2', { method: 'POST' });
      if (!res.ok) {
        const body = await res.json();
        throw new Error(body.error ?? '추천 생성 실패');
      }
      return res.json();
    },
    onSuccess: (newData) => {
      queryClient.setQueryData(recommendationsKey.all, newData);
    },
  });

  // 저장본이 없으면(null) 최초 1회 자동 생성
  useEffect(() => {
    if (isSuccess && recommend == null && !autoGenerated.current) {
      autoGenerated.current = true;
      generate();
    }
  }, [isSuccess, recommend, generate]);

  // 생성 중 또는 저장본 없음 → 분석 링 노출
  const isBusy = generating || recommend == null;
  const [ringDone, setRingDone] = useState(true);

  useEffect(() => {
    if (isBusy) setRingDone(false); // 로딩 시작하면 분석 링 리셋
  }, [isBusy]);

  if (isPending) return <SkeletonView />;

  // 로드 실패
  if ((loadError || generateError) && recommend == null) {
    return (
      <div className="py-20 text-center">
        <EmptyState
          icon={<WifiOff className="h-12 w-12 text-gray-400" strokeWidth={1.5} />}
          title="추천을 불러오지 못했어요"
          description={(loadError ?? generateError)?.message ?? '잠시 후 다시 시도해 주세요.'}
          showButton={false}
        />
        <Button label="다시 시도" onClick={() => generate()} className="mt-3" />
      </div>
    );
  }

  // 분석 진행 링
  if (isBusy || !ringDone) {
    return <AnalyzingLoader isReady={!isBusy} onComplete={() => setRingDone(true)} />;
  }

  // 여기부터 recommend는 non-null (isBusy에서 null 걸러짐)
  if (recommend == null) return <SkeletonView />;

  // 콜드스타트 (취향 없음)
  if (recommend.coldStart) {
    return (
      <EmptyState
        icon={<Compass className="h-12 w-12 text-[#af5858]" strokeWidth={1.5} />}
        title="아직 분석할 취향이 없어요"
        description={`마음에 드는 책에 좋아요나 북마크를 남겨보세요.\n취향을 읽고 딱 맞는 책을 추천해드릴게요.`}
        buttonLabel="책 둘러보기"
        href="/"
        className="mt-5"
      />
    );
  }

  const COOLDOWN = 10 * 60 * 1000; // 서버랑 동일하게 10분
  const lastGen = recommend.created_at ? new Date(recommend.created_at).getTime() : 0;
  const cooldownLeftMs = COOLDOWN - (Date.now() - lastGen);
  const onCooldown = cooldownLeftMs > 0;
  const leftMin = Math.ceil(cooldownLeftMs / 60000);

  return (
    <div className="w-full mx-auto py-8">
      {/* 취향 분석 */}
      <section className="mb-8">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-2xl font-bold">✨ 취향 맞춤 추천</h2>
          <Button
            variant="secondary"
            size="xs"
            label={onCooldown ? `${leftMin}분 후 가능` : '다시 추천 받기'}
            isLoading={generating}
            disabled={onCooldown}
            loadingText="생성중..."
            onClick={() => generate()}
          />
        </div>

        {recommend.taste_summary && (
          <div className="rounded-xl border bg-[#faf6f2] p-6">
            <p className="leading-relaxed">{recommend.taste_summary}</p>
          </div>
        )}
        {generateError && <p className="mt-2 text-sm text-red-500">{generateError.message}</p>}
      </section>

      {/* 추천 도서 */}
      <section>
        {recommend.label && <h3 className="mb-3 text-lg font-bold">{recommend.label}</h3>}
        <div className="flex gap-4 overflow-x-auto">
          <MarqueeRow books={recommend.recommendations} direction={'left'} />
        </div>
      </section>
    </div>
  );
};

export default RecommendContainer;
