import Button from '@/components/common/ui/Button';
import { recommendationsKey } from '@/shared/domain/recommend/queryKeys';
import { RecommendDataType } from '@/shared/domain/recommend/types';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useRef, useState } from 'react';
import { SkeletonView } from './SkeletonVIew';
import MarqueeRow from './MarqueeRow';
import { HOUR } from '@/shared/constants/time';
import EmptyState from '@/components/common/EmptyState';
import { Compass, RefreshCw, WifiOff } from 'lucide-react';
import AnalyzingLoader from './AnalyzingLoader';

const RecommendContainer = () => {
  const queryClient = useQueryClient();
  const autoGenerated = useRef(false);
  const {
    data: recommendData,
    error: recommendDataError,
    isPending: recommendPending,
    isSuccess,
  } = useQuery<RecommendDataType | null>({
    queryKey: recommendationsKey.all,
    queryFn: async () => {
      const response = await fetch('/api/recommend', { method: 'GET' });

      if (!response.ok) {
        const body = await response.json();
        throw new Error(body.error ?? 'AI 호출 실패');
      }
      const data = await response.json();

      return data;
    },
    staleTime: 1000 * 60 * 5,
  });

  const {
    mutate,
    isPending: generating,
    error: generateError,
  } = useMutation({
    mutationFn: async () => {
      const response = await fetch('/api/recommend', { method: 'POST' });
      if (!response.ok) {
        const body = await response.json();

        throw new Error(body.error ?? 'AI 호출 실패');
      }
      return response.json();
    },
    onSuccess: (newData) => {
      queryClient.setQueryData(recommendationsKey.all, newData);
    },
  });

  useEffect(() => {
    if (isSuccess && recommendData == null && !autoGenerated.current) {
      autoGenerated.current = true;
      mutate();
    }
  }, [isSuccess, recommendData, mutate]);

  const isGenerating = generating || recommendData === null; // 생성중 또는 데이터 없음
  const [ringDone, setRingDone] = useState(true); // 이미 로드된 데이터는 바로 노출(true)

  useEffect(() => {
    if (isGenerating) setRingDone(false); // 로딩 시작하면 분석링 리셋
  }, [isGenerating]);

  if (recommendPending) return <SkeletonView />;

  if ((recommendDataError || generateError) && recommendData == null) {
    return (
      <div className="py-20 text-center">
        <EmptyState
          icon={<WifiOff className="h-12 w-12 text-gray-400" strokeWidth={1.5} />}
          title="추천을 불러오지 못했어요"
          description={(recommendDataError ?? generateError)?.message ?? '잠시 후 다시 시도해 주세요.'}
          showButton={false}
          className="py-20"
        />
        <Button label="다시 시도" onClick={() => mutate()} className="mt-3" />
      </div>
    );
  }
  if (isGenerating || !ringDone) {
    return <AnalyzingLoader isReady={!isGenerating} onComplete={() => setRingDone(true)} />;
  }
  if ('coldStart' in recommendData) {
    return (
      <EmptyState
        icon={<Compass className="h-12 w-12 text-[#af5858]" strokeWidth={1.5} />}
        title="아직 분석할 취향이 없어요"
        description={`마음에 드는 책에 좋아요나 북마크를 남겨보세요.\nAI가 취향을 읽고 딱 맞는 책을 추천해드릴게요.`}
        buttonLabel="책 둘러보기"
        href="/"
        className="mt-5"
      />
    );
  }

  const lastGen = recommendData.created_at ? new Date(recommendData.created_at).getTime() : 0;
  const cooldownLeftMs = 1 * HOUR - (Date.now() - lastGen);
  const onCooldown = cooldownLeftMs > 0;
  const leftMin = Math.ceil(cooldownLeftMs / 60000);

  const groups = recommendData.recommendations.filter((g) => g.books.length > 0);
  return (
    <div className="w-full mx-auto py-8">
      {/* 취향 분석 */}
      <section className="mb-10">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-2xl font-bold mb-4">✨ AI가 분석한 독서 취향</h2>
          <Button
            variant="secondary"
            size="xs"
            label={onCooldown ? `${leftMin}분 후 가능` : '다시 추천 받기'}
            disabled={onCooldown}
            isLoading={generating}
            loadingText="생성중..."
            onClick={() => mutate()}
          />
        </div>

        <div className="rounded-xl border bg-[#faf6f2] p-6">
          <p className="leading-relaxed">{recommendData.taste_summary}</p>
        </div>
        {generateError && <p className="mt-2 text-sm text-red-500">{generateError.message}</p>}
      </section>

      {/* 추천 도서 */}
      {groups.length === 0 ? (
        <div className="py-20 text-center text-gray-500">
          <EmptyState
            icon={<RefreshCw className="h-12 w-12 text-gray-400" strokeWidth={1.5} />}
            title="추천을 고르지 못했어요"
            description={`지금은 딱 맞는 책을 찾지 못했어요.\n잠시 후 다시 시도하면 새로 골라드릴게요.`}
            showButton={false}
          />
          <div className="mt-4 flex justify-center">
            <Button label="다시 추천 받기" disabled={onCooldown} onClick={() => mutate()} />
          </div>
        </div>
      ) : (
        groups.map((group, i) => (
          <section key={group.label} className="mb-8">
            <h3 className="mb-3 text-lg font-bold">{group.label}</h3>
            <MarqueeRow books={group.books} direction={i % 2 === 0 ? 'left' : 'right'} />
          </section>
        ))
      )}
    </div>
  );
};

export default RecommendContainer;
