import EmptyState from '@/components/common/EmptyState';
import Button from '@/components/common/ui/Button';
import { recommendationsKey } from '@/shared/domain/recommend/queryKeys';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Flame, Heart, RefreshCcw, Sparkles, WifiOff } from 'lucide-react';
import { useCallback, useEffect, useMemo, useRef } from 'react';
import { RailBook } from '@/shared/domain/rails/types';
import { useMyStatus } from '@/hooks/book/useMyStatus';
import { useBookStats } from '@/hooks/book/useBookStats';
import BookRail from './BookRail';
import { RailsSkeleton } from './RailsSkeleton';
import { useRails } from '@/hooks/rails/useRails';

const RecommendRails = () => {
  const queryClient = useQueryClient();
  const autoGenerated = useRef(false);

  const { data, error, isPending } = useRails();

  const {
    mutate: generate,
    isPending: generating,
    error: generateError,
  } = useMutation({
    mutationFn: async () => {
      const res = await fetch('/api/recommend-v2/rail', { method: 'POST' });
      if (!res.ok) {
        const body = await res.json();
        throw new Error(body.error ?? '추천 생성 실패');
      }
      return res.json();
    },
    onSuccess: (newData) => {
      queryClient.setQueryData(recommendationsKey.rail(), newData);
    },
  });

  const { mutate: reroll, isPending: rerolling } = useMutation({
    mutationFn: async () => {
      const res = await fetch('/api/recommend-v2/rail', { method: 'PATCH' });
      if (!res.ok) {
        const body = await res.json();
        throw new Error(body.error ?? '새로추천받기 실패');
      }
      const data = await res.json();
      return data;
    },
    onSuccess: (newData) => {
      queryClient.setQueryData(recommendationsKey.rail(), newData);
    },
  });

  const isbnList = useMemo(
    () =>
      data ? [...new Set([...data.trending.books, ...data.sniping, ...data.anchor.books].map((b) => b.isbn13))] : [],
    [data]
  );

  const { data: statsMap } = useBookStats(isbnList);
  useMyStatus(isbnList);
  const attach = useCallback(
    (books: RailBook[]) => books.map((book) => ({ ...book, stats: statsMap?.[book.isbn13] })),
    [statsMap]
  );

  const sniping = useMemo(() => attach(data?.sniping ?? []), [data, attach]);
  const anchor = useMemo(() => attach(data?.anchor.books ?? []), [data, attach]);
  const trending = useMemo(() => attach(data?.trending.books ?? []), [data, attach]);

  useEffect(() => {
    if (data === null && !autoGenerated.current) {
      autoGenerated.current = true;
      generate();
    }
  }, [data, generate]);

  if (isPending || generating) return <RailsSkeleton />;

  if (error || generateError) {
    return (
      <div className="py-20 text-center">
        <EmptyState
          icon={<WifiOff className="h-12 w-12 text-gray-400" strokeWidth={1.5} />}
          title="추천을 불러오지 못했어요"
          description={(error ?? generateError)?.message ?? '잠시 후 다시 시도해 주세요.'}
          showButton={false}
        />
        <Button label="다시 시도" onClick={() => generate()} className="mt-3" />
      </div>
    );
  }

  if (!data) return <RailsSkeleton />;
  return (
    <section className="space-y-8">
      <div className="flex items-end justify-between">
        <div>
          <h2 className="text-2xl font-extrabold tracking-tight text-gray-900 sm:text-3xl">
            오늘, 뭐 읽지<span className="text-indigo-600">?</span>
          </h2>
          <p className="mt-1 text-sm text-gray-500">취향을 읽고 골라봤어요</p>
        </div>
        <Button
          label={<RefreshCcw className="w-4 h-4 transition-transform group-hover:rotate-180 duration-300" />}
          size="sm"
          variant="secondary"
          className="group"
          onClick={() => reroll()}
          isLoading={rerolling}
          disabled={rerolling}
        />
      </div>
      {/* 데이터기반 '평균' 내서 책추천 */}
      <BookRail icon={<Sparkles className="h-4 w-4" />} label="당신만을 위한 취향 저격" books={sniping} />

      {/* 제일좋아하는 책 타겟하여 책추천 */}
      <BookRail
        icon={<Heart className="h-4 w-4" />}
        label={
          <span>
            『<span className="text-indigo-600">{data.anchor.title}</span>』을 좋아한다면
          </span>
        }
        books={anchor}
      />
      {/* 제일좋아하는 책의 카테고리위주로 책추천 */}
      <BookRail
        icon={<Flame className="h-4 w-4" />}
        label={
          <span>
            <span className="text-indigo-600">{data.trending.categoryName ?? '요즘'}</span>
            {' 분야에서 뜨는 책'}
          </span>
        }
        books={trending}
      />
    </section>
  );
};

export default RecommendRails;
