export const RESULT_CODE = {
  // ==================auth==================

  // 로그인 성공
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  // 로그인 실패
  // (이메일 없음 / 비밀번호 불일치 등 통합 처리)
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',

  // 로그아웃 성공
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  // 로그아웃 실패
  AUTH_LOGOUT_FAILED: 'AUTH_LOGOUT_FAILED',

  // 회원가입 성공
  AUTH_SIGNUP_SUCCESS: 'AUTH_SIGNUP_SUCCESS',
  //회원가입 실패
  AUTH_SIGNUP_FAILED: 'AUTH_SIGNUP_FAILED',

  //회원탈퇴 성공
  AUTH_DELETE_SUCCESS: 'AUTH_DELETE_SUCCESS',
  //회원탈퇴 실패
  AUTH_DELETE_FAILED: 'AUTH_DELETE_FAILED',
  //아이디 변경
  AUTH_EMAIL_SAME_AS_CURRENT: 'AUTH_EMAIL_SAME_AS_CURRENT',

  //닉네임 변경
  AUTH_NICKNAME_SAME_AS_CURRENT: 'AUTH_NICKNAME_SAME_AS_CURRENT',

  //비밀번호 리셋 성공
  AUTH_RESET_PASSWORD_SUCCESS: 'AUTH_RESET_PASSWORD_SUCCESS',

  // 이미 존재하는 이메일
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  // 이미 존재하는 닉네임
  AUTH_NICKNAME_ALREADY_EXISTS: 'AUTH_NICKNAME_ALREADY_EXISTS',
  //회원가입 자동 로그인오류
  AUTH_AUTO_LOGIN_FAILED: 'AUTH_AUTO_LOGIN_FAILED',

  //로그인이후 댓글작성가능
  AUTH_REQUIRED_LOGIN: 'AUTH_REQUIRED_LOGIN',

  //로그인세션 만료안내
  AUTH_SESSION_EXPIRING_SOON: 'AUTH_SESSION_EXPIRING_SOON',

  //==========소셜로그인==========
  AUTH_SOCIAL_LOGIN_SUCCESS: 'AUTH_SOCIAL_LOGIN_SUCCESS',

  AUTH_SOCIAL_LOGIN_FAILED: 'AUTH_SOCIAL_LOGIN_FAILED',

  // ==================validation==================

  // 이메일 형식 오류
  VALIDATION_INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',

  // 비밀번호 형식 오류
  VALIDATION_INVALID_PASSWORD: 'VALIDATION_INVALID_PASSWORD',

  // 비밀번호 확인 불일치
  VALIDATION_PASSWORD_MISMATCH: 'VALIDATION_PASSWORD_MISMATCH',

  //닉네임 비여있음
  VALIDATION_REQUIRED_NICKNAME: 'VALIDATION_REQUIRED_NICKNAME',

  //이메일 비여있음
  VALIDATION_REQUIRED_EMAIL: 'VALIDATION_REQUIRED_EMAIL',

  //비밀번호 비여있음
  VALIDATION_REQUIRED_PASSWORD: 'VALIDATION_REQUIRED_PASSWORD',

  //비밀번호 컨펌 비여있음
  VALIDATION_REQUIRED_CONFIRM_PASSWORD: 'VALIDATION_REQUIRED_CONFIRM_PASSWORD',

  //아바타 업로드파일 형식
  VALIDATION_INVALID_IMAGE_FILE: 'VALIDATION_INVALID_IMAGE_FILE',

  //아바타 용량초과
  VALIDATION_IMAGE_FILE_TOO_LARGE: 'VALIDATION_IMAGE_FILE_TOO_LARGE',

  //현재비밀번호 확인
  VALIDATION_REQUIRED_PREV_PASSWORD: 'VALIDATION_REQUIRED_PREV_PASSWORD',

  //태그 입력가능 길이 제한
  VALIDATION_TAG_MAX_LENGTH_EXCEEDED: 'VALIDATION_TAG_MAX_LENGTH_EXCEEDED',

  //검색어 입력
  VALIDATION_REQUIRED_SEARCHKEYWORD: 'VALIDATION_REQUIRED_SEARCHKEYWORD',
  ////=================페이지네이션//=================

  //페이지 네이션
  PAGINATION_PAGE_OUT_OF_RANGE: 'PAGINATION_PAGE_OUT_OF_RANGE',

  //=================댓글==================

  //댓글 실패
  COMMENT_CREATE_FAILED: 'COMMENT_CREATE_FAILED',

  //댓글 내용이 비여있음
  COMMENT_REQUIRED_CONTENT: 'COMMENT_REQUIRED_CONTENT',
  //최대 ** 자까지 입력가능 안내
  COMMENT_MAX_LENGTH_EXCEEDED: 'COMMENT_MAX_LENGTH_EXCEEDED',
  //최대 **줄까지 입력가능 안내
  COMMENT_MAX_LINE_EXCEEDED: 'COMMENT_MAX_LINE_EXCEEDED',
  //붙여넣기 제한 안내
  COMMENT_PASTE_LIMIT_EXCEEDED: 'COMMENT_PASTE_LIMIT_EXCEEDED',

  //=================북마크==================
  BOOKMARK_MEMO_SAVE_FAILED: 'BOOKMARK_MEMO_SAVE_FAILED',

  BOOKMARK_MEMO_DELETE_FAILED: 'BOOKMARK_MEMO_DELETE_FAILED',

  //=================북마크 태그==================
  TAG_INVALID_CHARACTER: 'TAG_INVALID_CHARACTER',

  TAG_MAX_COUNT_EXCEEDED: 'TAG_MAX_COUNT_EXCEEDED',

  TAG_ALREADY_EXISTS: 'TAG_ALREADY_EXISTS',

  //=================약관 동의==================

  //필수동의 항목을 동의안내
  TERMS_REQUIRED_AGREEMENT: 'TERMS_REQUIRED_AGREEMENT',

  //==================server error==================
  COMMON_SERVER_ERROR: 'COMMON_SERVER_ERROR',

  COMMON_UNKNOWN_ERROR: 'COMMON_UNKNOWN_ERROR',

  COMMON_FILE_UPLOAD_CANCELLED: 'COMMON_FILE_UPLOAD_CANCELLED',
} as const;

export type ResultCode = (typeof RESULT_CODE)[keyof typeof RESULT_CODE];
